#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"

echo "Installing Postgres ..."
  brew install postgres --no-python

echo "Installing Redis ..."
  brew install redis
  
echo "Installing MongoDB ..."
  brew install mongodb

echo "Installing Memcached ..."
  brew install memcached

echo "Installing ImageMagick ..."
  brew install imagemagick

echo "Installing RVM (Ruby Version Manager) ..."
  bash < <(curl -sk https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
  echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function' >> ~/.bash_profile
  source ~/.bash_profile

bash < <(curl -s https://raw.github.com/guusen/laptop/master/ruby)
